name: CI

on: [push]

jobs:
  RunTests:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        python-version: ["3.9", "3.14"]
        exclude:
          - os: macos-latest
            python-version: '3.9'
        include:
          - python-version: '3.9'
            module-versions: "numpy==1.21 scipy==1.9 matplotlib==3.3 pandas==1.3 jinja2 joblib==1.1 numba==0.53 meson ninja pytest setuptools==69"
          - python-version: '3.14'
            module-versions: "numpy scipy matplotlib pandas jinja2 joblib numba meson ninja pytest"
        toolchain:
          - {compiler: gcc, version: 'latest'}
    steps:
      - uses: actions/checkout@v3
      - name: Setup Fortran Compiler
        uses: fortran-lang/setup-fortran@v1
        if: runner.os == 'MacOS'
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ${{ matrix.module-versions }}
          python PTkinetics/ramploading_for.py -h
      - name: Run tests
        run: pytest -s tests/

